name: Automated Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  java-tests:
    name: Java API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Maven tests
        run: mvn test

      - name: Generate Allure static report
        if: always()
        run: |
          mvn io.qameta.allure:allure-maven:report

      - name: Configure AWS credentials
        if: always()
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.SSKEYAWS }}
          aws-secret-access-key: ${{ secrets.SECRETSSKEY }}
          aws-region: us-east-2

      - name: Upload Allure report to AWS S3
        if: always()
        run: |
          aws s3 sync target/site/allure-maven-plugin s3://brasil-api-allure/runs/${{ github.run_id }} --delete

      - name: Generate Summary
        if: always()
        run: |
          REPORT_URL="http://brasil-api-allure.s3-website.us-east-2.amazonaws.com/runs/${{ github.run_id }}/index.html"

          echo "### 📊 Resultado da Execução" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Item | Valor |" >> $GITHUB_STEP_SUMMARY
          echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
          echo "| Status | Testes finalizados |" >> $GITHUB_STEP_SUMMARY
          echo "| Relatório Allure | [Abrir relatório]($REPORT_URL) |" >> $GITHUB_STEP_SUMMARY

  cypress-tests:
    name: Cypress API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
