name: Automated Tests

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  java-tests:
    name: Java API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: Run Maven tests
        run: mvn test

      - name: Allure Server
        run: allure serve allure-results

      - name: Generate Summary
      if: always()
      run: |
        echo "### 📊 Resultado da Execução" >> $GITHUB_STEP_SUMMARY
        echo "| Status | Descrição |" >> $GITHUB_STEP_SUMMARY
        echo "| :--- | :--- |" >> $GITHUB_STEP_SUMMARY
        echo "| ✅ | Testes Finalizados |" >> $GITHUB_STEP_SUMMARY
        echo "Relatório completo disponível nos artefatos." >> $GITHUB_STEP_SUMMARY

  cypress-tests:
    name: Cypress API Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Run Cypress tests
        run: npx cypress run
